### ISSUE TITLE
ADL files segfaults adplug (adplay)

### ISSUE THREAD

**Issue by DarkDefender** [adplug/adplug#6]
I think I'm having the same problem as this bug in the old bugtracker:
http://sourceforge.net/p/adplug/bugs/81/

I'm trying to play the Lands of Lore .ADL files (with the current master version of adplug) and all of them seem to manage to get adplug to segfault:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ba4823 in AdlibDriver::snd_readByte(__va_list_tag (&) [1]) () from /usr/lib64/libadplug-2.3.so.0
(gdb) bt
#0  0x00007ffff7ba4823 in AdlibDriver::snd_readByte(__va_list_tag (&) [1]) () from /usr/lib64/libadplug-2.3.so.0
#1  0x00007ffff7ba4f66 in AdlibDriver::callback(int, ...) () from /usr/lib64/libadplug-2.3.so.0
#2  0x00007ffff7ba6c55 in CadlPlayer::play(unsigned char) () from /usr/lib64/libadplug-2.3.so.0
#3  0x00007ffff7ba6dcd in CadlPlayer::rewind(int) () from /usr/lib64/libadplug-2.3.so.0
#4  0x00007ffff7ba6fc6 in CadlPlayer::load(std::string const&, CFileProvider const&) () from /usr/lib64/libadplug-2.3.so.0
#5  0x00007ffff7b7678e in CAdPlug::factory(std::string const&, Copl*, CPlayers const&, CFileProvider const&) () from /usr/lib64/libadplug-2.3.so.0
#6  0x0000000000402ae0 in main ()
```

I also tried to run valgrind, but valgrind seems to lack support for my cpu as it complains about unsuppored instructions. So I won't get any help from valgrind...

Perhaps @cspiegel can give some insight as he dug around in the adl code recently.

**Comment by cspiegel** [comment]
I was able to (on master) play, without trouble, a sampling of the Dune/Kyrandia ADL files provided at the link above.  I don't have any Lands of Lore ADL files, so if you can provide a link to those, I'd be willing to take a look.  However, AdLib file formats are not well documented and I'm not especially familiar with the code, so it may come to nothing.

**Comment by DarkDefender** [comment]
@cspiegel Doesn't "KYRA3A.ADL" segfault for you? All other Kyrandia files seem to play fine for me. But that one segfaults.

**Comment by cspiegel** [comment]
I must have missed that one, thanks; it does segfault.  I'll see if I can find anything.

**Comment by DarkDefender** [comment]
Thanks! I can provide the Lands of Lore files also if you want them later.

**Comment by DarkDefender** [comment]
I could also donate so you can buy it on GOG if you want ;)

**Comment by cspiegel** [comment]
Hah, thanks for the offer, but I dug up my copy of LoL and was able to reproduce the problem.  There's good news and bad news.

Good: I got the LoL ADL files working.
Bad: There are multiple versions of ADL files which are not completely compatible, and there is no identifying information in the files to determine which is which.  I'm looking at heuristics to try to figure out how to determine the version, but I'm not sure it's possible.  As it is, if LoL ADLs work, then other ADLs stop working; you have to choose one version to support.

One possibility is to support “versioned” ADL extensions, like .adl1, .adl2, etc.  This would require end-user effort, unfortunately.  Currently, because there's no identifying information in the file, Adplug just assumes that an extension of .adl is an ADL file.

The Kyrandia file segfaults for a different reason; I know why, and a fix shouldn't be too tough, but I haven't worked on it yet.

**Comment by DarkDefender** [comment]
Ah, ok I see. Perhaps you could have a check see if the player would segfault by looking at the data read from the file, then try the other ADL versions if it would cause a segfault? I don't know really what the cause of the segfault were so perhaps it's not an easy or viable thing to do.

You could also just catch the segfault and print that the file is probably adl2 and then exit.

**Comment by binarymaster** [comment]
>One possibility is to support “versioned” ADL extensions, like .adl1, .adl2, etc. This would require end-user effort, unfortunately. Currently, because there's no identifying information in the file, Adplug just assumes that an extension of .adl is an ADL file.

Here is some technical information...
http://www.vgmpf.com/Wiki/index.php?title=ADL#Technical

Maybe it's also possible to use https://github.com/adplug/database to store filenames for each format version, as it was done for imf/wlf files?

**Comment by cspiegel** [comment]
> Perhaps you could have a check see if the player would segfault by looking at the data read from the file

Ideally that would work; it might be possible to determine, without trying to play the file, whether some table indices are out of range for specific ADL versions, narrowing down the possibilities.

A bigger problem is that there are, according to ScummVM's ADL code, 4 different ADL versions: Eye of the Beholder 1, Eye of the Beholder 2, Kyrandia 1, and Lands of Lore/Kyrandia 2.  But I'll see what I can do.

> Maybe it's also possible to use https://github.com/adplug/database to store filenames for each format version, as it was done for imf/wlf files?

This is a good suggestion, and may be the only real option.  If I can't reliably determine the different versions of ADL by looking at the files, I'll take a look at adding DB support for them.

**Comment by Malvineous** [comment]
What I had to do with many of the [Camoto](http://www.shikadi.net/camoto) formats was parse the data at the start, looking for out of range values.  Things like "does this offset point past the end of the file" or "if this list of values ends with zeroes, are there non-zero values towards the end" and that kind of thing.  I'm not sure whether that would work here, but it has turned out to be a pretty reliable way of identifying formats with no headers.

The down side is that you end up having two different parsers for the data - one to identify the format, and another to actually process (play) the content.

**Comment by cspiegel** [comment]
> What I had to do with many of the Camoto formats was parse the data at the start, looking for out of range values.

This is exactly the approach I took, and it seems promising.

@DarkDefender, I've created a test branch [here](https://github.com/cspiegel/adplug/tree/adl-versions), if you'd like to take it for a spin.  The issue with `kyra3a.adl` is still there, but Lands of Lore ADL files should work.  As a bonus, I've got at least some support for Eye of the Beholder 1 ADL files (`adlib.dat` and `sound.dat`) in there as well.

I'm planning on taking another look and cleaning some stuff up tomorrow, but let me know if you have any success with this branch.  If it looks OK, once I get it cleaned up, I'll create a pull request.

**Comment by DarkDefender** [comment]
It seems to be able to read the lands of lore ADL files now. I've only tried LORE01[A-C].ADL though. However I noticed a few things:

Sometimes the first note of the song is wrong (or at least sounds out of place). It is less noticeable in some songs. But with subsong 4 in LORE01C.ADL it's quite obvious.

There are also some other problems with playback,
-s 3 LORE01C.ADL  //note stuck 
-s 3 LORE01B.ADL //strange first play through
-s 9 LORE01B.ADL //note gets stuck in the middle with the wrong instrument.

Is there a way to get the available number of subsongs? It seems that after a while no new songs are available and it plays one from earlier. A good example is in LORE01B.ADL were everything above 10 seems to be the same.

**Comment by DarkDefender** [comment]
Hmm, seems like there is some other issues with playback also.

Listen to the default subsong in LORE02A.ADL and compair it to this:
https://youtu.be/4YHPdjtwFrM

Granted the youtube one was probably recorded with DOSbox or something. But in adplug the organ like instrument has distinct volume breaks. IE the when playing a sequence of notes (0:28 to 0:45 in the youtube vid) the note following the current one seems to start out at volume 0 and then rapidly climbs up to the expected value. The note seems to "pop" also.

I'm guessing this might be related to the OPL emulation so I don't know if this is ADL specific...

**Comment by cspiegel** [comment]
It's entire possible (probable, really) that there are some glitches in the LoL playback code.  I updated it with some rather simple changes based on ScummVM's ADL support (which is where AdPlug's ADL code originally came from), but there's some bits in ScummVM which aren't present in AdPlug now.

At some point in time I'd like to look at all the changes made in ScummVM since the import and see how feasible it would be to rework AdPlug's ADL support based on that.  Such an undertaking would be more involved than the changes I've recently made, though.

Until then, however, this is probably as good as I can make it.  As for the OPL emulation, you might try hacking adplay to use CWemuopl instead of CEmuopl; CWemuopl is new since 2.2 and comes from DOSBox.  If there are OPL issues, this might help with them.

**Comment by cspiegel** [comment]
> Is there a way to get the available number of subsongs?

Subsongs are detected, but detection for LoL subsongs is broken (thanks for pointing that out: I missed the subsong detection code when adding LoL).

But I'm not convinced the subsong detection is quite right even in the original case, at least with my limited ADL knowledge.  The first 120 bytes of the file are indices into a table, and those indices are used to determine subsongs.  An index of 255 means that the subsong is invalid, so the ADL code looks backward from the end and looks for the first non-255 value, then assumes that that is the last subsong.  ADL files, though, don't require that there be valid indices followed by invalid indices: the beginning of `kyra1a.adl` looks like this:

`
00 01 02 09 10 FF FF FF FF FF 8F FF
`
So there are valid, invalid, valid, invalid, in no sort of order.  It would appear that the ADL code (which walks backward) is not correct: pretending the excerpt above is the full set of indices, it would stop at 8F, and say there are 11 subsongs, when there really look to be 6.  LoL looks the same (it uses 16-bit indices, but the idea is the same: 0xffff is invalid, others are valid).

A quick sampling indicates that subsongs up to the first invalid index seem to be “good”, whereas later indices, even if they appear valid (not 0xff/0xffff), tend to not sound right.

I'll try to spend more time working on subsongs, but I'm flying pretty blind here.

**Comment by DarkDefender** [comment]
I guess the best thing to do would be to get all valid indices and store them. So the kyra1a.adl example would become:
```
00 01 02 09 10 8F
```

I'm guessing that the later subsongs might be left over from development. Or perhaps some unused songs were at the now blank locations and were removed, but they didn't change the index number of the songs because they didn't want to change code in the game. So now we have these blank ranges.

I mean, it seems to me like the .ADL files has been sliced into portions that reprecents the game progression. IE the LORE01 files are from the beginning of the game etc. So perhaps they just moved out songs to other files during development also.

Anyways, I really appreciate the time you're investing into this.

**Comment by Malvineous** [comment]
Probably a good idea to check whether *any* of the post-0xFF songs are valid.  It's possible that 0xFF was a terminator code (like ending a string with 0x00), and anything after the first 0xFF is just whatever was left over in memory at the time.  It's equally possible all the slots are valid, and 0xFF is just a flag to indicate an unused slot.

If most of the post-0xFF subsongs sound wrong, it's probably the former, and subsong scanning can go from the start until the first 0xFF.  But if you can find just one proper subsong after an 0xFF entry, then they are almost certainly slots and all non-0xFF entries are valid subsongs.

Alternatively you could try to change the first subsong to 0xFF, then run one of the games with that modified file.  If the song no longer plays, then you know 0xFF is a terminator.  But if the song still plays (except maybe one of the subsongs doesn't) then you'll know it's a list of slots.

**Comment by cspiegel** [comment]
> Probably a good idea to check whether any of the post-0xFF songs are valid. It's possible that 0xFF was a terminator code (like ending a string with 0x00), and anything after the first 0xFF is just whatever was left over in memory at the time. It's equally possible all the slots are valid, and 0xFF is just a flag to indicate an unused slot.

In all the files I've sampled, they're “valid” in that they don't point beyond the bounds of the array.  This is especially telling in LoL files, because they're 16-bit values that cannot exceed 500, and none do.  If it were leftover junk, it'd be a bit surprising if all were < 500.

>If most of the post-0xFF subsongs sound wrong, it's probably the former, and subsong scanning can go from the start until the first 0xFF. But if you can find just one proper subsong after an 0xFF entry, then they are almost certainly slots and all non-0xFF entries are valid subsongs.

Assuming they're being played correctly, there's a mixture.  kyra1b, for example, has an 0xff byte followed by lots of tracks which are perfectly valid.  kyra5b has bytes following an 0xff which sound like they play a sound effect and then jump to the same area, which plays an obnoxious “song” which may be the interpretation of junk data.  Hard to say.

Basically, at this point I have no idea.

> Alternatively you could try to change the first subsong to 0xFF, then run one of the games with that modified file. If the song no longer plays, then you know 0xFF is a terminator. But if the song still plays (except maybe one of the subsongs doesn't) then you'll know it's a list of slots.

The first two bytes of version 3 ADL files look to always be 0x01 and 0x02.  The ADL code sets the default subsong to 2 as a result, and plays that.  I have a Dune 2 ADL file (dune ii - 05.adl) which has 0xff as the 2nd subsong (i.e. the first one the ADL code tries to play).  When played, there's no sound.  However, there is a non-0xff byte a bit later on (subsong 6) which plays properly when selected.  So it's pretty clear you can't just stop at the first 0xff byte, even if *that* byte is an invalid index.

It may make sense to start counting subsongs at offset 2, ignoring any 0xff bytes.  It'd be easy enough to keep a table of valid subsongs, if that's indeed how this works.  I'll try to find some time to look at that.

**Comment by DarkDefender** [comment]
Just a quick update on the LORE02A.ADL sound issue:

I switched to CWemuopl and I think it is a bit better. However it's not totally fine still. It more obvious that something is not right on subsong 4 in the LORE02A.ADL. The instruments are off and after the first playthough the song then plays at 1/4 (I think) of the intended speed.

**Comment by NY00123** [comment]
Just a small note about the OPL emulation, totally unrelated to playback of ADL files (IMF may be more relevant in my case): I've also recently tried to modify adplay-unix so CWemuopl can be used, but I think it's not yet sufficiently close to the original.

It looks like the version of WoodyOPL included in this repository dates back to 2008, and is older than the revision originally added to DOSBox. I've sent an email to Simon Peter asking for a few details about the WoodyOPL revision he's added, and am still waiting for an answer.

**Comment by NY00123** [comment]
This is a bit of a late reply for me (more-or-less 1 month late), but I've gotten an answer from Simon. As I've guessed, he got the 2008 revision of Woody's emulator before a later 2009 revision was included in DOSBox, and the same 2008 revision was adapted for AdPlug. It was much later (2014) when this was finally added-and-committed to the public adplug repository (at least according to the git log).

**Comment by binarymaster** [comment]
Today I've inspected available file examples from each game, here are results in the table:
http://www.shikadi.net/moddingwiki/ADL_Format

Also I wrote a program that correctly reads any ADL file (there are 3 known versions):
https://gist.github.com/binarymaster/40ca7c61122fabbafe6849f5891a50fd

Unfortunately I have very few experience in C++, so this can be implemented by @cspiegel 
(although I will try :)

**Comment by DarkDefender** [comment]
@binarymaster thank you for your work!
I would just like to point out that the playback of the Lands of Lore .ADL files are still not 100% correct though. I'm still getting stuck notes, weird first playthroughs and wrong instruments in certain songs.

I'm guessing that some of these problems must be problems with opening and reading the file correctly.

```
There are also some other problems with playback,
-s 3 LORE01C.ADL //note stuck 
-s 3 LORE01B.ADL //strange first play through
-s 9 LORE01B.ADL //note gets stuck in the middle with the wrong instrument.
```

**Comment by binarymaster** [comment]
There can be issues with ScummVM ADL replaying code.

Latest code of replayer is here:
https://github.com/scummvm/scummvm/blob/0a5a722b027303e29b486e146a580f7881ca2a2d/engines/kyra/sound_adlib.cpp

I tested with Winamp plugin, and detected another problem - in some files it plays the same subsong (index 2) along with the selected subsong (obviously not the song but sound effect).

Although, pattern and instrument offsets should be read correctly for each version now.

**Comment by binarymaster** [comment]
@DarkDefender 
>```
>-s 3 LORE01B.ADL //strange first play through
>```

Just checked, it seems to be ok for me.

>```
>-s 3 LORE01C.ADL //note stuck
>-s 9 LORE01B.ADL //note gets stuck in the middle with the wrong instrument.
>```

These sounds like short effects.

Do you have original recordings of these songs, so I can compare it with AdPlug output?

**Comment by DarkDefender** [comment]
@binarymaster I just realized that I were not using the git version of adplay (but I did use the master version of adplug).

After I updated to the git version I noticed that the default OPL emulator changed from satoh to woody. It seems like woody does not have these problems. (I totally forgot that I should be using the woody one in the first place ><)

However, as I previously discovered the 4th subsong in LORE02A.ADL plays a lot slower then intended after the first playthough still.

Sadly, I do not have the RAW / DRO files for the songs with problems :(

**Comment by tomas** [comment]
I just ran into the famous segfault on the master branch, so I think this bug should be reopened. 

If it helps, I did some investigation and the specific line that seems to be triggering the segfault is [this one](https://github.com/adplug/adplug/blob/master/src/adl.cpp#L786). At that point it seems that the value of `dataptr` is 0, and so is `channel.duration`. `channel.position` is 253.

**Comment by binarymaster** [comment]
@tomas which .ADL file did you tested?

**Comment by binarymaster** [comment]
Maybe we need to sync code with ScummVM? I didn't checked for updates in their repository.

**Comment by tomas** [comment]
`KYRA4B.ADL` also seems to provoke the segfault, by the way.

**Comment by tomas** [comment]
Just found out an odd thing. My web player, which uses a JS version of adplug thanks to Emscripten, *can* actually play `KYRA3A.ADL` and `KYRA4B.ADL`, but only if no other songs have been played with Adplug before (neither ADL nor other).

In other words, if you open the [web page](http://muki.io) and drag any of the two into the window, they will play without any problems. But if you play any other ADL file (or LAA, DRO, etc) then boom.

Does that help in figuring out what may be going on?

**Comment by Malvineous** [comment]
That usually means it's a memory corruption error.  You could try running `adplay` through Valgrind and see if it reports any bad memory accesses when playing the suspect file - that may at least narrow down the location of the problem.

**Comment by binarymaster** [comment]
By the way, please check if PR #29 also fixes this issue.

**Comment by adambiser** [comment]
I have been trying to track down this bug and I think I'm on the right track.

At the end of _load_, cursubsong is set to -1.  When rewind() is called after loading, the default subsong for the call is -1.  Inside rewind we have:
`  if(subsong == -1) subsong = cursubsong;`
So subsong and cursubsong are both -1 at this point.

Then we reach
`playSoundEffect(subsong); // subsong == -1`
playSoundEffect converts the track (subsong) parameter from signed int -1 to uint16_t 0xfff and passes 0xffff onto play(track);

When we reach `soundId = _trackEntries[track];` or `soundId = _trackEntries16[track];`, an access violation occurs since the length of _trackEntries and _trackEntries16 are 120 and 250 respectively.

I have this happen with Winamp plugin v1.8.2.

This does not occur in playertest because it never calls rewind(), it goes straight to update(), which in turn calls rewind(2) when cursubsong == -1.

**Comment by binarymaster** [comment]
Seems like this have been fixed in https://github.com/adplug/adplug/commit/3753629e918f84222c0dc816a41b25ef7f14e20c by @adambiser. Please retest on the latest [CI build](https://github.com/adplug/winamp/releases/download/ci/in_adlib.dll).

I just played several ADL tunes consequently without a crash. :slightly_smiling_face:

**Comment by adambiser** [comment]
The three test ADLs play in Winamp now.
I tried KYRA3A.ADL and still get a crash, but in a different location: snd_ReadByte.
